// Code generated by goctl. DO NOT EDIT.
package types

type Register struct {
	Name     string `json:"name"`
	Password int32  `json:"password"`
}

type Token struct {
	Atoken  string `json:"atoken"`
	Rtoken  string `json:"rtoken"`
	Version int32  `json:"version"`
}

type Update struct {
	Id       int    `json:"id"`       //唯一id
	Name     string `json:"name"`     //需要更新的名字
	Password int32  `json:"password"` //需要更新的密码
	Atoken   string `json:"atoken"`   //解析version的token
}

type State struct {
	Onestring string `json:"onestring"` //返回的状态
}
